@baseUrl = http://localhost:3333
@authToken = {{getToken.response.body.token}}


###
# @name getToken
POST {{baseUrl}}/sessions/password
Content-Type: application/json

{
  "email": "edu@email.com",
  "password": "87654321"
}

###
# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Eduardo Santana",
  "email": "edu@email.com",
  "password": "12345678"
}


###

GET {{baseUrl}}/profile 
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email": "edu@email.com",
}

